name: pokemon_challenge
description: pokemon challenge exercise solution
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.6
  go_router: ^13.0.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.0
  pretty_dio_logger: ^1.3.1
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
